export const AUTH_USER = "AUTH_USER"
export const ALL_CONTACT = "ALL_CONTACT"
export const CONTACT_DETAILS = "CONTACT_DETAILS"
export const ALL_P_CONTACT = "ALL_P_CONTACT"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const ADD_CONTACT = "ADD_CONTACT"
export const OPEN_CONTACT_MODAL = "OPEN_CONTACT_MODAL"
export const CLOSE_CONTACT_MODAL = "CLOSE_CONTACT_MODAL"
export const SEARCH_CONTACT = "SEARCH_CONTACT"

export const ALL_DISTRICT = "ALL_DISTRICT"

export const ALL_SUBDISTRICT = "ALL_SUBDISTRICT"

export const UPDATE_CONTACT = "UPDATE_CONTACT"

export const All_PROJECT_CATEGORY = "All_PROJECT_CATEGORY"
export const ADD_PROJECT_CATEGORY = "ADD_PROJECT_CATEGORY"
export const UPDATE_PROJECT_CATEGORY = "UPDATE_PROJECT_CATEGORY"
export const DELETE_PROJECT_CATEGORY = "DELETE_PROJECT_CATEGORY"
export const SEARCH_PROJECT_CATEGORY = "SEARCH_PROJECT_CATEGORY"
export const ALL_P_PROJECT_CATEGORY = "ALL_P_PROJECT_CATEGORY"


export const All_PROJECT = "All_PROJECT"
export const ADD_PROJECT = "ADD_PROJECT"
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const DELETE_PROJECT = "DELETE_PROJECT"
export const SEARCH_PROJECT = "SEARCH_PROJECT"

export const ALL_PURPOSE = "ALL_PURPOSE"
export const ADD_PURPOSE = "ADD_PURPOSE"
export const UPDATE_PURPOSE = "UPDATE_PURPOSE"
export const DELETE_PURPOSE = "DELETE_PURPOSE"
export const ALL_P_PURPOSE = "ALL_P_PURPOSE"
export const SEARCH_PURPOSE = "SEARCH_PURPOSE"

export const ALL_PARENT_ACCOUNT = "ALL_PARENT_ACCOUNT"
export const ALL_ACCOUNT_TYPE = "ALL_ACCOUNT_TYPE"
export const ALL_ACCOUNT_TYPE2 = "ALL_ACCOUNT_TYPE2"

export const ALL_INCOME = "ALL_INCOME"
export const ADD_INCOME = "ADD_INCOME"
export const UPDATE_INCOME = "UPDATE_INCOME"
export const DELETE_INCOME = "DELETE_INCOME"
export const SEARCH_INCOME = "SEARCH_INCOME"

export const ALL_EXPENSE = "ALL_EXPENSE"
export const ADD_EXPENSE = "ADD_EXPENSE"
export const UPDATE_EXPENSE = "UPDATE_EXPENSE"
export const DELETE_EXPENSE = "DELETE_EXPENSE"
export const SEARCH_EXPENSE = "SEARCH_EXPENSE"

export const ALL_INVOICE = "ALL_INVOICE"
export const ADD_INVOICE = "ADD_INVOICE"
export const UPDATE_INVOICE = "UPDATE_INVOICE"
export const DELETE_INVOICE = "DELETE_INVOICE"
export const SEARCH_INVOICE = "SEARCH_INVOICE"
export const UNPAID_INVOICE = "UNPAID_INVOICE"

export const ALL_INSTALLMENT_INVOICE = "ALL_INSTALLMENT_INVOICE"



// payment received
export const ADD_PAYMENT_RECEIVE = "ADD_PAYMENT_RECEIVE";
export const UPDATE_PAYMENT_RECEIVE = "UPDATE_PAYMENT_RECEIVE";
export const DELETE_PAYMENT_RECEIVE = "DELETE_PAYMENT_RECEIVE";
export const ALL_PAYMENT_RECEIVE = "ALL_PAYMENT_RECEIVE";

// recuiting
export const ALL_VISA = "ALL_VISA"
export const ADD_VISA = "ADD_VISA"
export const CUSTOMER_VISA = "CUSTOMER_VISA"
export const DELETE_VISA = "DELETE_VISA"
export const GETLASTID = "GETLASTID"
export const REGISTER_USER = "REGISTER_USER"
export const LOGIN_USER = "LOGIN_USER"
export const FORGOT_USER = "FORGOT_USER"
export const RESET_USER = "RESET_USER"

export const ALL_USER_ROLE = "ALL_USER_ROLE"
export const ALL_USER_ROLE2 = "ALL_USER_ROLE2"
export const ADD_USER_ROLE = "ADD_USER_ROLE"
export const UPDATE_USER_ROLE = "UPDATE_USER_ROLE"
export const DELETE_USER_ROLE = "DELETE_USER_ROLE"

export const ALL_USER_ROLE_INFO = "ALL_USER_ROLE_INFO"
export const UPDATE_ASSIGN_USER_ROLE = "UPDATE_ASSIGN_USER_ROLE"

export const ROLE_PERMISSION = "ROLE_PERMISSION"
export const ROLE_PERMISSION_UPDATE = "ROLE_PERMISSION_UPDATE"

export const CURRENT_LEADGER = "CURRENT_LEADGER"
export const SEARCH_LEADGER = "SEARCH_LEADGER"

export const STATISTICS = "STATISTICS"
export const REPORT = "REPORT"

export const SEARCH_WORKERS="SEARCH_WORKERS"

//Area
export const All_AREA = "All_AREA"
export const ADD_AREA = "ADD_AREA"
export const UPDATE_AREA = "UPDATE_AREA"
export const DELETE_AREA = "DELETE_AREA"
export const SEARCH_AREA = "SEARCH_AREA"

//Category
export const All_NCATEGORY = "All_NCATEGORY"
export const ADD_NCATEGORY = "ADD_NCATEGORY"
export const UPDATE_NCATEGORY = "UPDATE_NCATEGORY"
export const DELETE_NCATEGORY = "DELETE_NCATEGORY"
export const SEARCH_NCATEGORY = "SEARCH_NCATEGORY"

//Topic
export const All_TOPIC = "All_TOPIC"
export const ADD_TOPIC = "ADD_TOPIC"
export const UPDATE_TOPIC = "UPDATE_TOPIC"
export const DELETE_TOPIC = "DELETE_TOPIC"
export const SEARCH_TOPIC = "SEARCH_TOPIC"

//Gallery
export const All_GALLERY = "All_GALLERY"
export const ADD_GALLERY = "ADD_GALLERY"
export const UPDATE_GALLERY = "UPDATE_GALLERY"
export const DELETE_GALLERY = "DELETE_GALLERY"
export const SEARCH_GALLERY = "SEARCH_GALLERY"


// Content Management
export const GET_CONTENT = "GET_CONTENT"
export const ADD_CONTENT = "ADD_CONTENT"
export const DELETE_CONTENT = "DELETE_CONTENT"

//site

export const FETCH_SITE_INFOS = "FETCH_SITE_INFOS"
export const ADD_SITE_INFO = "ADD_SITE_INFO"
export const DELETE_SITE_INFO = "DELETE_SITE_INFO"
export const SET_SITE_INFOS = "SET_SITE_INFOS"



