export const SET_AUTH_USER = "SET_AUTH_USER"
export const SET_CONTACT = "SET_CONTACT"
export const SET_CONTACT_DETAILS = "SET_CONTACT_DETAILS"
export const SET_P_CONTACT = "SET_P_CONTACT"
export const AFTER_DELETE_CONTACT = "AFTER_DELETE_CONTACT"
export const AFTER_ADD_CONTACT = "AFTER_ADD_CONTACT"
export const SET_DISTRICT = "SET_DISTRICT"
export const SET_SUBDISTRICT = "SET_SUBDISTRICT"
export const DISTRICT_LOADER = "DISTRICT_LOADER"
export const SUBDISTRICT_LOADER = "SUBDISTRICT_LOADER"
export const AFTER_UPDATE_CONTACT = "AFTER_UPDATE_CONTACT"
export const SET_CONTACT_MODAL = "SET_CONTACT_MODAL"

export const SET_PROJECT_CATEGORY = "SET_PROJECT_CATEGORY"
export const AFTER_ADD_PROJECT_CATEGORY = "AFTER_ADD_PROJECT_CATEGORY"
export const AFTER_UPDATE_PROJECT_CATEGORY = "AFTER_UPDATE_PROJECT_CATEGORY"
export const AFTER_DELETE_PROJECT_CATEGORY = "AFTER_DELETE_PROJECT_CATEGORY"
export const SET_P_PROJECT_CATEGORY = "SET_P_PROJECT_CATEGORY"


export const SET_PROJECT = "SET_PROJECT"
export const AFTER_ADD_PROJECT = "AFTER_ADD_PROJECT"
export const AFTER_UPDATE_PROJECT = "AFTER_UPDATE_PROJECT"
export const AFTER_DELETE_PROJECT = "AFTER_DELETE_PROJECT"

export const SET_PURPOSE = "SET_PURPOSE"
export const AFTER_ADD_PURPOSE = "AFTER_ADD_PURPOSE"
export const AFTER_UPDATE_PURPOSE = "AFTER_UPDATE_PURPOSE"
export const AFTER_DELETE_PURPOSE = "AFTER_DELETE_PURPOSE"
export const SET_P_PURPOSE = "SET_P_PURPOSE"

export const SET_PARENT_ACCOUNT = "SET_PARENT_ACCOUNT"
export const SET_ACCOUNT_TYPE = "SET_ACCOUNT_TYPE"
export const SET_ACCOUNT_TYPE2 = "SET_ACCOUNT_TYPE2"

export const SET_INCOME = "SET_INCOME"
export const AFTER_ADD_INCOME = "AFTER_ADD_INCOME"
export const AFTER_UPDATE_INCOME = "AFTER_UPDATE_INCOME"
export const AFTER_DELETE_INCOME = "AFTER_DELETE_INCOME"

export const SET_EXPENSE = "SET_EXPENSE"
export const AFTER_ADD_EXPENSE = "AFTER_ADD_EXPENSE"
export const AFTER_UPDATE_EXPENSE = "AFTER_UPDATE_EXPENSE"
export const AFTER_DELETE_EXPENSE = "AFTER_DELETE_EXPENSE"

export const SET_INVOICE = "SET_INVOICE"
export const AFTER_ADD_INVOICE = "AFTER_ADD_INVOICE"
export const AFTER_UPDATE_INVOICE = "AFTER_UPDATE_INVOICE"
export const AFTER_DELETE_INVOICE = "AFTER_DELETE_INVOICE"
export const SET_UNPAID_INVOICE = "SET_UNPAID_INVOICE"

// payment received
export const SET_ADD_PAYMENT = "SET_ADD_PAYMENT";
export const SET_ALL_PAYMENT_RECEIVE = "SET_ALL_PAYMENT_RECEIVE";
export const SET_ADD_PAYMENT_RECEIVE = "SET_ADD_PAYMENT_RECEIVE";
export const AFTER_UPDATE_PAYMENT = "AFTER_UPDATE_PAYMENT";
export const AFTER_DELETE_PAYMENT = "AFTER_DELETE_PAYMENT";

//recuiting
export const SET_ALL_VISA = "SET_ALL_VISA"
export const SET_ADD_VISA = "SET_ADD_VISA"
export const SET_DELETE_VISA = "SET_DELETE_VISA"
export const SET_GETLASTID = "SET_GETLASTID"
export const SET_CUSTOMER_VISA = "SET_CUSTOMER_VISA"


export const SET_REGISTER_NOTIFIACTION = "SET_REGISTER_NOTIFIACTION"
export const SET_LOGIN_NOTIFIACTION = "SET_LOGIN_NOTIFIACTION"
export const SET_USER_INFO = "SET_USER_INFO"
export const SET_FORGOT_PASSWORD_NOTIFIACTION = "SET_FORGOT_PASSWORD_NOTIFIACTION"
export const SET_RESET_PASSWORD_NOTIFIACTION = "SET_RESET_PASSWORD_NOTIFIACTION"

export const SET_USER_ROLE = "SET_USER_ROLE"
export const SET_USER_ROLE2 = "SET_USER_ROLE2"
export const AFTER_ADD_USER_ROLE = "AFTER_ADD_USER_ROLE"
export const AFTER_UPDATE_USER_ROLE = "AFTER_UPDATE_USER_ROLE"
export const AFTER_DELETE_USER_ROLE = "AFTER_DELETE_USER_ROLE"

export const SET_USER_ROLE_INFO = "SET_USER_ROLE_INFO"
export const AFTER_UPDATE_ASSIGN_USER_ROLE = "AFTER_UPDATE_ASSIGN_USER_ROLE"


export const SET_ROLE_PERMISSION = "SET_ROLE_PERMISSION"
export const AFTER_UPDATE_ROLE_PERMISSION = "AFTER_UPDATE_ROLE_PERMISSION"

export const SET_CURRENT_LEADGER = "SET_CURRENT_LEADGER"

export const SET_STATISTICS = "SET_STATISTICS"
export const SET_REPORT = "SET_REPORT"


export const SET_SEARCH_WORKERS="SET_SEARCH_WORKERS"

//Area
export const SET_AREA = "SET_AREA"
export const AFTER_ADD_AREA = "AFTER_ADD_AREA"
export const AFTER_UPDATE_AREA = "AFTER_UPDATE_AREA"
export const AFTER_DELETE_AREA = "AFTER_DELETE_AREA"

//Newsportal Category
export const SET_NCATEGORY = "SET_NCATEGORY"
export const AFTER_ADD_NCATEGORY = "AFTER_ADD_NCATEGORY"
export const AFTER_UPDATE_NCATEGORY = "AFTER_UPDATE_NCATEGORY"
export const AFTER_DELETE_NCATEGORY = "AFTER_DELETE_NCATEGORY"

//Topic
export const SET_TOPIC = "SET_TOPIC"
export const AFTER_ADD_TOPIC = "AFTER_ADD_TOPIC"
export const AFTER_UPDATE_TOPIC = "AFTER_UPDATE_TOPIC"
export const AFTER_DELETE_TOPIC = "AFTER_DELETE_TOPIC"

//Gallery
export const SET_GALLERY = "SET_GALLERY"
export const AFTER_ADD_GALLERY = "AFTER_ADD_GALLERY"
export const AFTER_UPDATE_GALLERY = "AFTER_UPDATE_GALLERY"
export const AFTER_DELETE_GALLERY = "AFTER_DELETE_GALLERY"

//Gallery Content
export const SET_GALLERYC = "SET_GALLERYC"
export const AFTER_ADD_GALLERYC = "AFTER_ADD_GALLERYC"
export const AFTER_UPDATE_GALLERYC = "AFTER_UPDATE_GALLERYC"
export const AFTER_DELETE_GALLERYC = "AFTER_DELETE_GALLERYC"

// Content Management
export const SET_GET_CONTENT = "SET_GET_CONTENT"
export const SET_ADD_CONTENT = "SET_ADD_CONTENT"
export const SET_DELETE_CONTENT = "SET_DELETE_CONTENT"



